spring.application.name=bancobienestar
#Definir puerto
server.port=8080
#configuracion de thaymylify
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8


#configuracion d ela base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/bienestar_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en la consola
spring.jpa.show-sql=true
# Formatea las consultas SQL
spring.jpa.properties.hibernate.format_sql=true
# Dialecto de MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Opcional: nombre de la aplicación